Housekeeping
sorokya/reoserv pull request #173
Opened 2024-09-22 00:10 UTC by chrzrdx

2024-09-22 13:24 UTC, sorokya requested changes
Requested some changes to the README otherwise looks great! Thanks @chrzrdx 😊

2024-09-22 13:24 UTC, sorokya commented on README.md
> +The Rust-powered server emulator for [Endless Online](https://game.eoserv.net/) 🦀
I should have fixed this a while ago but can you change the URL here to https://endless-online.com

2024-09-22 13:24 UTC, sorokya commented on README.md
> +- [Docker](https://docs.docker.com/engine/install/)
Docker isn't required for building the server. Just recommended for running in dev environments

2024-09-22 13:24 UTC, sorokya commented on README.md
> +- `debug`: This will print human-readable data structures for every packet.
This is no longer true, I removed the debug packet printing a while back :P

I'm pretty sure trace will print raw byte arrays though

2024-09-22 13:24 UTC, sorokya commented on README.md
> +## Setup quests, NPCs and items for your server
We can add a link to the docs here

```
See [docs](https://reoserv.net/docs/pubs) for help
```

2024-09-22 15:31 UTC, chrzrdx commented on README.md
> +- `debug`: This will print human-readable data structures for every packet.
So, should we remove the RUST_LOG flag completely (as a configuration option for the user)?

2024-09-22 19:37 UTC, sorokya commented on README.md
> +- `debug`: This will print human-readable data structures for every packet.
I guess it doesn't need to be exposed no

2024-09-23 17:17 UTC, chrzrdx commented
@sorokya We can also consider moving eo-client to its own repository, and link to that in the docs (or in CONTRIBUTING.md)

2024-10-10 19:49 UTC, merged